### ISSUE TITLE
Trouble running graphql cli after install. 

### ISSUE THREAD

**Issue by weshicks** [Urigo/graphql-cli#321]
Hi All. 

This might be more of an issue with my system than `graphql-cli`, but I'm not certain so I figured I'd post this here. 

I just installed `graphql-cli` via `npm install -g graphql-cli`, and the install seems to successfully complete. After installing running any `graphql` command produces this error: 

```
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOTDIR: not a directory, scandir '/usr/local/bin/node'
    at Object.fs.readdirSync (fs.js:904:18)
    at listPluggings (/Users/whicks/.nvm/versions/node/v8.9.4/lib/node_modules/graphql-cli/src/index.ts:32:10)
    at arrayMap (/Users/whicks/.nvm/versions/node/v8.9.4/lib/node_modules/graphql-cli/node_modules/lodash/lodash.js:639:23)
    at Function.map (/Users/whicks/.nvm/versions/node/v8.9.4/lib/node_modules/graphql-cli/node_modules/lodash/lodash.js:9554:14)
    at interceptor (/Users/whicks/.nvm/versions/node/v8.9.4/lib/node_modules/graphql-cli/node_modules/lodash/lodash.js:16991:35)
    at thru (/Users/whicks/.nvm/versions/node/v8.9.4/lib/node_modules/graphql-cli/node_modules/lodash/lodash.js:8795:14)
    at /Users/whicks/.nvm/versions/node/v8.9.4/lib/node_modules/graphql-cli/node_modules/lodash/lodash.js:4388:28
    at arrayReduce (/Users/whicks/.nvm/versions/node/v8.9.4/lib/node_modules/graphql-cli/node_modules/lodash/lodash.js:683:21)
    at baseWrapperValue (/Users/whicks/.nvm/versions/node/v8.9.4/lib/node_modules/graphql-cli/node_modules/lodash/lodash.js:4387:14)
    at LazyWrapper.lazyValue [as value] (/Users/whicks/.nvm/versions/node/v8.9.4/lib/node_modules/graphql-cli/node_modules/lodash/lodash.js:1873:16)
    at baseWrapperValue (/Users/whicks/.nvm/versions/node/v8.9.4/lib/node_modules/graphql-cli/node_modules/lodash/lodash.js:4385:25)
    at LodashWrapper.wrapperValue (/Users/whicks/.nvm/versions/node/v8.9.4/lib/node_modules/graphql-cli/node_modules/lodash/lodash.js:9050:14)
    at Object.installCommands (/Users/whicks/.nvm/versions/node/v8.9.4/lib/node_modules/graphql-cli/src/index.ts:43:6)
    at Object.<anonymous> (/Users/whicks/.nvm/versions/node/v8.9.4/lib/node_modules/graphql-cli/src/bin.ts:8:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

To me this looks like a permissions issue of some sort, but I don't recall having this issue with any other  globally installed npm packages. I checked `/usr/local/bin/` and that's where node is installed on my machine. Things of note: I'm using `nvm` to manage my node version, and I installed `graphql-cli` under node 8.9.4 which is the highest version of node I currently have installed on my system. 

(If this isn't the appropriate place to ask about this, feel free to close this issue!)

**Comment by JamieMason** [comment]
I also have this issue, digging into it I think the problem might be with this dependency

```
var npmPaths = require("npm-paths");
```

The return value of `npmPaths()` is upstream of `listPluggings` and is what ends up being passed to `fs.readdirSync` and causing the error.

The return value of `npmPaths()` is:

```
[ '/Users/foldleft/.nvm/versions/node/v10.15.0/bin/node',
  '/Users/foldleft/Dev/node_modules',
  '/Users/foldleft/node_modules',
  '/Users/node_modules',
  '/node_modules' ]
```

Looking at the README on https://github.com/jonschlinkert/npm-paths I think only paths to `node_modules` directories should be returned.

**Comment by jonschlinkert** [comment]
A PR would be great, thanks!

**Comment by ardatan** [comment]
Currently we have new structure for GraphQL CLI and in the new alpha version `4.0.0-alpha.0` 
Checkout new instructions and we will be happy to hear your feedback. 
Feel free to contact us using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
We have just released a new structure for GraphQL CLI in new alpha versions `4.0.0-alpha.XXX`.

This was a complete rewrite and we've updated all the dependencies.

Can you please check it out and see if that issue is still relevant?

Checkout the [new instructions](https://github.com/urigo/graphql-cli#usage--initialization) and the [migration guide](https://github.com/urigo/graphql-cli#migration-from-3xx-to-4xx) on the docs and let us know your feedback. 

Feel free to contact us by opening an issue or using our Discord channel;
https://discord.gg/xud7bH

**Comment by Urigo** [comment]
I've posted the wrong Discord link, this is the correct one: https://discord.gg/xud7bH9
