### ISSUE TITLE
graphql init => MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by jycouet** [Urigo/graphql-cli#600]
**Describe the bug**
When I do a `graphql init` I get an error: **MODULE_NOT_FOUND.**

**To Reproduce**
1. `yarn global add graphql-cli@canary`
```
success Installed "graphql-cli@4.0.0-alpha-0f3d52d.34" with binaries:
      - graphql
Done in 29.72s.
```
2. `graphql init`
```
{ Error: Cannot find module '@test-graphql-cli/init-plugin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at resolveFileName (C:\Users\JYC\AppData\Local\Yarn\Data\global\node_modules\resolve-from\index.js:29:39)
    at resolveFrom (C:\Users\JYC\AppData\Local\Yarn\Data\global\node_modules\resolve-from\index.js:43:9)
    at module.exports (C:\Users\JYC\AppData\Local\Yarn\Data\global\node_modules\resolve-from\index.js:46:47)
    at possibleNames.concat.concat.possibleNames.map.name (C:\Users\JYC\AppData\Local\Yarn\Data\global\node_modules\graphql-cli\dist\get-plugin.js:12:123)
    at Array.map (<anonymous>)
    at Object.getPluginByName (C:\Users\JYC\AppData\Local\Yarn\Data\global\node_modules\graphql-cli\dist\get-plugin.js:12:111)
    at Object.cli (C:\Users\JYC\AppData\Local\Yarn\Data\global\node_modules\graphql-cli\dist\cli.js:14:43)
    at Object.<anonymous> (C:\Users\JYC\AppData\Local\Yarn\Data\global\node_modules\graphql-cli\dist\index.js:6:7)
    at Module._compile (internal/modules/cjs/loader.js:778:30) code: 'MODULE_NOT_FOUND' }
```

**Versions**
 - OS: `Windows 10`
 - `graphql-cli`: `4.0.0-alpha-0f3d52d.34` (installed with `yarn global add graphql-cli@canary`)

**Additional context**
Hint 1: I don't know if it's helping but, I checked and I have the package `@test-graphql-cli` but I don't see init-plugin... only init.
![image](https://user-images.githubusercontent.com/5312607/68063267-cf1fb380-fccc-11e9-9bcd-8e5c45d9800b.png)

Hint 2: Windows?

**Comment by ardatan** [comment]
Could you try that again by reinstalling the latest canaryz?

**Comment by jycouet** [comment]
Well done, with the latest canary `4.0.0-alpha-3daf270.35` it's doing though now. 
Thx 👍
